# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/hypr/fullconf/animations.conf #
source = ~/.config/hypr/fullconf/autostart.conf #not done
source = ~/.config/hypr/fullconf/binds.conf # need to make the reload commands 
source = ~/.config/hypr/fullconf/decoration.conf #
source = ~/.config/hypr/fullconf/environments.conf #also cursor
source = ~/.config/hypr/fullconf/input.conf #
source = ~/.config/hypr/fullconf/layouts.conf #
source = ~/.config/hypr/fullconf/monitor.conf #
source = ~/.config/hypr/fullconf/variables.conf #has misc and gestures 
source = ~/.config/hypr/fullconf/windowrules.conf #

#source = ~/.config/hypr/conf/variables.conf
#source = ~/.config/hypr/conf/tablet.conf #
#source = ~/.config/hypr/conf/plugins.conf 
# Modifying these configs can be done by creating a user defined config in the home directory, e.g.
## ~/.config/hypr/config/user-config.conf
# source = ~/.config/hypr/config/user-config.conf
