preload = /home/lelle/.config/wallpapers/asukaBg.png
preload = /home/lelle/.config/wallpapers/reze.png
preload = /home/lelle/.config/wallpapers/bandage.jpg
wallpaper {
    monitor = eDP-1
    path = /home/lelle/.config/wallpapers/bandage.jpg
    fit_mode = fill
}
