# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = se
    kb_variant = ,qwerty
    kb_model =
    kb_options = grp:lctrl_lwin_toggle    
    kb_rules =
    
    # scroll_method = on_button_down
    # scroll_button_lock = true

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = -0.45 # -1.0 - 1.0, 0 means no modification.
}
